### ISSUE TITLE
Update to newest tidyr version 1.2.0

### ISSUE THREAD

**Issue by M-Colley** [mjockers/syuzhet#43] opened 2023-04-14 15:02 UTC
Hey, thank you for your package!

Unfortunately, it does not work with the newest version of tidyr anymore.

Here is the problem: 

`Warning message:
`spread_()` was deprecated in tidyr 1.2.0.
ℹ Please use `spread()` instead.
ℹ The deprecated feature was likely used in the syuzhet package.`

Kind regards

**Comment by mjockers** [comment] 2023-04-21 13:26
Closing as duplicate of #43

**Closed by mjockers** 2023-04-21 13:26 UTC
